### ISSUE TITLE
Clearing the search bar directs to wrong URL

### ISSUE THREAD

**Issue by fbernhart** [simple-icons/simple-icons-website#20]
### Kind of issue

- [ ] Improvement
- [x] Bug
- [ ] Other, namely:

### Description
Visiting https://ericcornelissen.github.io/simple-icons-website, if I type something into the search bar and then clear it (clicking on the small "x") it somehow redirects me to https://ericcornelissen.github.io instead of back to https://ericcornelissen.github.io/simple-icons-website (while still displaying the website correctly 🤔).

Therefore after clearing the search bar, downloading an icon fails, as the "SVG" button no longer points to https://ericcornelissen.github.io/simple-icons-website/icons/42.svg but now to https://ericcornelissen.github.io/icons/42.svg.

Tested on Chrome (89.0.4381.6) on Ubuntu (20.10).

**Comment by ericcornelissen** [comment]
Can confirm this behaviour, the same happens when you clear the search query by just hitting backspace.

Actually, the main website has the exact same problem - however, as it is served from the website root this is not a problem. So by serving this at [simpleicons.org](https://simpleicons.org/) the problem would be solved :upside_down_face: Still, I'll fix it :+1:

**Comment by ericcornelissen** [comment]
Fixed with 3247684db85858cabfd3a971baed116f55a78c28
