### ISSUE TITLE
Update Open Graph image

### ISSUE THREAD

**Issue by fbernhart** [simple-icons/simple-icons-website#21]
### Kind of issue 

- [ ] Feature
- [x] Bug
- [ ] Design
- [ ] Other, namely:

### Description

Would be great to have an updated screenshot for the PNG file at: https://github.com/ericcornelissen/simple-icons-website/blob/master/public/images/og.png (which is still showing the old website).

**Comment by ericcornelissen** [comment]
Thanks for the issue, hadn't opened it as I consider it a _duplicate_ (of sorts) of https://github.com/simple-icons/simple-icons/issues/1368 but don't mind having a separate issue of this nature here as well. Rather than replacing the `og.png` with a screenshot of the new website I would favor the image that is decided upon in that issue.

**Comment by ericcornelissen** [comment]
Going to close this now with 9249d978df02422aded8d9275bfd2b2ad459c60a and leave the remaining discussion to https://github.com/simple-icons/simple-icons/issues/1368
