### ISSUE TITLE
Support both alphabetical and colored ordering for non-JS users

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-website#34]
### Kind of issue 

- [x] Improvement (when JS is disabled)
- [ ] Bug
- [ ] Other, namely:

### Description

Currently, if JavaScript is disabled, the user only has alphabetical ordering available. We could support color-based ordering for non-JS users by generating a second version of the website where color-based ordering is the default and converting [the buttons to choose the ordering method](https://github.com/simple-icons/simple-icons-website/blob/42bab7dbdf3311eca8e0273d9532169ed2e9f454/public/index.pug#L58-L69) into links to the respectively ordered page for non-JS users.

I think we should support this, provided we can do so with minimum effort for keeping the two versions of the page in sync when [the .pug source](https://github.com/simple-icons/simple-icons-website/blob/42bab7dbdf3311eca8e0273d9532169ed2e9f454/public/index.pug) is changed. E.g. by somehow instructing how the icons should be ordered in [the webpack configuration](https://github.com/simple-icons/simple-icons-website/blob/42bab7dbdf3311eca8e0273d9532169ed2e9f454/webpack.config.js), and than just generating both versions.

**Comment by jorgeamadosoria** [comment]
I don't think this is all that necessary.
Is there a metric of how many users are in the case of not having JS but at the same time requiring this library?
Also, I think that if a user is navigating without JS, they are already prepared to accept a reduction of functionality in the websites they visit. Offering alpha sort is more than enough, imo.
I don't think this warrants action given the amount of open issues in this and the main repository. I would like a couple more maintainers to offer an opinion to see whether this can be closed or should it be keep open until such time as someone can get around to it.

**Comment by ericcornelissen** [comment]
I agree it's not essential, however I don't agree that we should just neglect users with JavaScript disabled if we can support it because they're used to it.

That said, as I said before, I don't think having open issues for something that you're not **against** is a problem. If you disagree, please go ahead and just close the issues that you think are too low priority to care about - there's no point in having this discussion for every issue like this.

Off topic, but as a comparison: People that need a11y features are probably also somewhat use to poor a11y support but we should still provide it. Unless you fundamentally believe people with JS disabled must have a worse experience, I see no reason to intentionally provide them with a worse service.

**Comment by jorgeamadosoria** [comment]
**if we can support it** 
I think we are already overextended. Therefore, no need to overextend ourselves even further. That's the rationale behind shedding or resolving as many open issues as possible. 
As for a11y, the problem with that is that such people would have a hard time accessing information without a11y features. The people navigating without JS are not only a minimal demographic, but also one that would be doing that either by choice or due to network / security constraints that would make them not the user demographic for this library.
And even after that, I don't advocate for making their experience worse (alpha sort is already in, and it's fine to keep it there). I advocate for not focusing in issues with minimal impact. 

And personally, color sorting is not something I think should exist at all, as I explained in other issues.

If it were up to me, I would focus more in reducing the amount of issues open, move to improve responsiveness and cross-browsing support, and assume everyone has JS installed. Adding a11y features is also a good idea, that could warrant its own low-priority ticket.

**Comment by ericcornelissen** [comment]
> if we can support it
> I think we are already overextended. Therefore, no need to overextend ourselves even further. That's the rationale behind shedding or resolving as many open issues as possible.
> As for a11y, the problem with that is that such people would have a hard time accessing information without a11y features. The people navigating without JS are not only a minimal demographic, but also one that would be doing that either by choice or due to network / security constraints that would make them not the user demographic for this library.
And even after that, I don't advocate for making their experience worse (alpha sort is already in, and it's fine to keep it there). I advocate for not focusing in issues with minimal impact.

Again, I'm not disagreeing with that assessment. From my point of view, having open issues that you don't plan to work on are not an inherent problem. If you disagree, by all means, close those issues.

> And personally, color sorting is not something I think should exist at all, as I explained in other issues.

If you want to don't want to loose track of issues, keep the discussion in them focused :wink: 


> If it were up to me, I would focus more in reducing the amount of issues open, move to improve responsiveness and cross-browsing support, and assume everyone has JS installed. Adding a11y features is also a good idea, that could warrant its own low-priority ticket.

If there are any issues with responsiveness, cross-browsers support, or a11y please do open issues but all of those should be pretty well-covered (with the exception of initial load time of the website, which I would put in a separate category "performance").

**Comment by jorgeamadosoria** [comment]
the menu is not responsive, for example.  That's one thing I'm waiting to work on when #99 is done

Initial load time is its own thing, and can't be worked on because the easiest way to tackle that is paginating the list of icons, which is next to impossible loading all icons as is the practice right now. We not using libraries does not help, either.

I will create a ticket to remove color sorting completely, then: #107

**Comment by ericcornelissen** [comment]
> the menu is not responsive, for example. That's one thing I'm waiting to work on when #99 is done

:+1: 

> Initial load time is its own thing, and can't be worked on because the easiest way to tackle that is paginating the list of icons, which is next to impossible loading all icons as is the practice right now. We not using libraries does not help, either.

If you think using a library is the silver bullet that will solve this problem, by all means go ahead and change it. However, you should probably have buy in from the team, plus I won't be helping with that.

**Comment by jorgeamadosoria** [comment]
> If you think using a library is the silver bullet that will solve this problem, by all means go ahead and change it. However, you should probably have buy in from the team, plus I won't be helping with that.

I don't think it's going to be a silver bullet, but it will certainly give us options. I know that jQuery for example is good for basic pagination. Or a simple library for loading on scroll. Or that kind of thing. What we lose in size because of adding the library we recoup with not loading all the icons at first access and in development speed.
Adding a library is something I will propose later, but not just yet. A lot to do in the menu first, then I'll jump into that. A few months from now, probably.

**Comment by jorgeamadosoria** [comment]
This conversation got derailed into different things. 
Coming back to the central thread now that a few months have passed: Can we close this ticket? No one seems interested to work or comment on it (I certainly aren't) and it's not really all that necessary to keep the core functionality of the website. 
The overextension argument stands, I think, and all the other comments made about different approaches. 
While having open tickets is not really a problem, it is discouraging having so many issues that no one is planning on taking on, specially if they are issues that are niche or not really essential.

----------------------
After a brief discussion with @ericcornelissen, I'll be closing this ticket in a few days, unless any other @simple-icons/maintainers has a different opinion on the matter?

**Comment by jorgeamadosoria** [comment]
Closed due to lack of followup.
