### ISSUE TITLE
Add link pointing to simple-icons-website repository

### ISSUE THREAD

**Issue by mondeja** [simple-icons/simple-icons-website#49]
### Kind of issue

- [x] Feature
- [ ] Bug
- [ ] Design
- [ ] Other, namely:

### Description
I miss a link that takes you to the web repository (this repository), as long as it does not confuse with the main repository. Do you see it too meta? Maybe it could be "hidden" at the end, like the Twitter share button ... :thinking:

**Comment by ericcornelissen** [comment]
I'm not sure what it is you're looking for. Why should there be a link to this repository on the website? Do you want people to show where they can find the source if they're interested (if so, the footer seems right)? Do you want to make sure people open an issue for the website in the correct repository (if so, I think we should just link to this repo the same way [this repo links to the main repo](https://github.com/simple-icons/simple-icons-website/issues/new/choose))? Anything else? 

To clarify, I'm not against it, just not sure why it is needed 🙂 

On a related note, I do think we can consider updating the link "GitHub" to point to `https://github.com/simple-icons` instead of `https://github.com/simple-icons/simple-icons` (relates to https://github.com/simple-icons/simple-icons-website/issues/27).

**Comment by mondeja** [comment]
> Why should there be a link to this repository on the website? Do you want people to show where they can find the source if they're interested (if so, the footer seems right)?

I don't say that "should", only seems to me that a buttton like "fork me on Github" it could help to link this repository from the website, perhaps for an user who wants to fix something at any given time, or just want to see how something is done, but obviously less intrusive that the typical "fork me on Github" in the corner.

> On a related note, I do think we can consider updating the link "GitHub" to point to `https://github.com/simple-icons` instead of `https://github.com/simple-icons/simple-icons`...

I agree :+1:

**Comment by ericcornelissen** [comment]
Apologies if my response seemed negative, I was genuinely asking why we would add it and listing reasons I could come up with; I just don't think we should add it just because "every" open source website has the _"Fork me on GitHub"_ banner or something similar :slightly_smiling_face: 

If you want to make it easier to find the source of the website to either look at it and to submit issues or fixes - beyond the link to GitHub in the header -then I'm definitely open to that. And I agree that it should not be too intrusive, as it isn't that important I would say. Maybe something in the footer with the right text so it is easily found with <kbd>Ctrl</kbd>+<kbd>F</kbd>?

**Comment by mondeja** [comment]
> Maybe something in the footer with the right text so it is easily found with <kbd>Ctrl</kbd>+<kbd>F</kbd>?

I agree with that, perhaps an "Edit on Github" link pointing to this repository would suffice.

**Comment by jorgeamadosoria** [comment]
I don't think this is terribly important or relevant to the end users. I'm not necessarily against it, but I wouldn't consider it a high priority or even a low priority item. 

I think that a link to the simple icons repo is important, because that's where the bulk of user contribution happens, and where the 3rd partiy links are, where the disclaimers and info on the icons are, etc.
The website is just a place to show the icons so the user can see them all or download them one by one. It hardly need a lot of user contribution, nor I think the end user will be generally interested in it.

The library is the product, the website is just the store window.

**Comment by ericcornelissen** [comment]
Do you think it's "bad" idea, or just not an important issue?

In case of the former, why do you think adding a link to this repo to make anyone interested aware they can contribute to the website is a bad idea? I don't think that is a problem for all the other users that just use the website to get the icon they need :thinking: 

In case of the latter, I don't think we disagree :smile: But having the issue doesn't strike me as a problem. Worst case scenario, it's just a reminder. Better case scenario, someone else had the same idea, finds this issue and :+1: it. Best case scenario, as it's labeled `good first issue`, we might get a contribution from someone new to the open source space.

**Comment by jorgeamadosoria** [comment]
it's not a bad idea. It's just not something I would even consider doing, high or low priority. If someone wants to add it, I don't mind it, but I don't see the menu missing anything if it's not there.

Also, I don't think it's a good first issue: technically, it's very simple, but design-wise, with all the things pending regarding the menu, it may not be the best issue to start with right now.
Maybe after the menu is a bit more defined, so the ambiguity between this link and the link to the main repo do not get confused.

**Comment by ericcornelissen** [comment]
> it's not a bad idea. It's just not something I would even consider doing, high or low priority. If someone wants to add it, I don't mind it,

I'm still slightly confused. When you say "it's just not something I would even consider doing" do you mean in general it's not something that should be added to the website, or just that you, personally, don't want to do the work. The rest of your comment suggests it's the latter, which is fine but I'm not sure why you bring that up.


> but I don't see the menu missing anything if it's not there.

I agree that it shouldn't go in the "menu" (presuming you mean the list of links in the header) and neither the issue description nor the discussion indicates that we should. As [I said before](https://github.com/simple-icons/simple-icons-website/issues/49#issuecomment-785078318) I think it's something we could add in the footer. (Possibly requiring some larger design changes to the footer.)


> Also, I don't think it's a good first issue: technically, it's very simple, but design-wise, with all the things pending regarding the menu, it may not be the best issue to start with right now.
> Maybe after the menu is a bit more defined, so the ambiguity between this link and the link to the main repo do not get confused.

That's definitely a fair point. It's a good first issue under the assumption that we agree on the design. I'll remove the label for now until we have some agreement on roughly where we would like the link **and** that is included in the issue description :+1:

**Comment by jorgeamadosoria** [comment]
> 
> I'm still slightly confused. When you say "it's just not something I would even consider doing" do you mean in general it's not something that should be added to the website, or just that you, personally, don't want to do the work. The rest of your comment suggests it's the latter, which is fine but I'm not sure why you bring that up.

I, personally, I'm completely indifferent to it. If brought up against literally any other work that needs to be done, it would be discarded in favor of that other piece of work. It would be something I'd add to the site only if everything else has been added already. 

> I agree that it shouldn't go in the "menu" (presuming you mean the list of links in the header) and neither the issue description nor the discussion indicates that we should. As [I said before](https://github.com/simple-icons/simple-icons-website/issues/49#issuecomment-785078318) I think it's something we could add in the footer. (Possibly requiring some larger design changes to the footer.)

The footer is a good place for this link. It's unobstructive enough. It should be noted however that some effort must be spend in making sure that the two repo links are not confused with each other.

> 
> That's definitely a fair point. It's a good first issue under the assumption that we agree on the design. I'll remove the label for now until we have some agreement on roughly where we would like the link **and** that is included in the issue description 👍

Agreed. After the menu is more agreed upon, then this is actually a very good first issue.

**Comment by jorgeamadosoria** [comment]
I think we can revisit this issue now that the menu is more settled design wise?
Maybe add the link in the footer with a Simple Icons logo?

**Comment by ericcornelissen** [comment]
> Maybe add the link in the footer with a Simple Icons logo?

I don't think that logo clearly conveys where it will take you, moreover, I wouldn't expect that to link to the website's repository.

**Comment by jorgeamadosoria** [comment]
> > Maybe add the link in the footer with a Simple Icons logo?
> 
> I don't think that logo clearly conveys where it will take you, moreover, I wouldn't expect that to link to the website's repository.

then better not add it at all? Because I just don't see which icon to use to differentiate two github links in the menu.

**Comment by ericcornelissen** [comment]
If the choice is between no link and icon link I would indeed go with no link. But a text link could work if we do want to add it. For example, something like "**Fork this website on GitHub**" or "This website is made with ❤️ on **GitHub**" (where the bold part would be a link). Just

**Comment by jorgeamadosoria** [comment]
> If the choice is between no link and icon link I would indeed go with no link. But a text link could work if we do want to add it. For example, something like "**Fork this website on GitHub**" or "This website is made with ❤️ on **GitHub**" (where the bold part would be a link). Just

In the footer, right? I could see this in the footer quite easily.

**Comment by ericcornelissen** [comment]
I would agree the footer makes the most sense, but I would be open to other suggestions as well

**Comment by jorgeamadosoria** [comment]
me too. Let's try the footer and see if other @simple-icons/maintainers have an opinion on it.

**Comment by dirien** [comment]
+1 on footer!

**Comment by sachinraja** [comment]
Sorry if I'm misunderstanding, but does this mean users have to scroll all the way down, past 2000 icons to see the link in the footer? If  so, I don't see much of a benefit in adding it there.

**Comment by mondeja** [comment]
> Sorry if I'm misunderstanding, but does this mean users have to scroll all the way down, past 2000 icons to see the link in the footer? If so, I don't see much of a benefit in adding it there.

Does it means that we should remove the entire footer because users "have to scroll all the way down"?

![image](https://user-images.githubusercontent.com/23049315/132546017-80ffb89d-2eb7-4e14-8d87-7788d8b72a44.png)

IMHO, I think that this is just an stylistic improvement, just to complete the displayed information. With the right keywords, using <kbd>Ctrl</kbd><kbd>F</kbd> would be enough. Truth be told, when I opened this little issue, I didn't expect there to be so much discussion for such a small change.

Anyways we can always add a second button later if on the footer does not convince.

**Comment by jorgeamadosoria** [comment]
> Sorry if I'm misunderstanding, but does this mean users have to scroll all the way down, past 2000 icons to see the link in the footer? If so, I don't see much of a benefit in adding it there.

Yes.
the problem is not that the link doesn't belong in the footer, but rather that the footer is almost invisible.
We could fix that anchoring the footer, or paginating the icons.
I actually favor pagination as a more sustainable solution. When the library gets to 5k icons or something like that the current approach is not going to scale terribly well.

But, these are different issues. For this one, a link on the footer is good enough, I think. I'm with @mondeja on this one: just stylistic, no need for it to be front and center.

**Comment by jorgeamadosoria** [comment]
I've added a PR for this link. Care to check, @sachinraja @mondeja @ericcornelissen @dirien ?
