### ISSUE TITLE
Add link to report outdated icons

### ISSUE THREAD

**Issue by jorgeamadosoria** [simple-icons/simple-icons-website#95]
### Kind of issue 

- [X] Feature
- [ ] Bug
- [ ] Design
- [ ] Other, namely:

We should make it easier for users to report outdated icons in an effort to keep our collection up-to-date. Based on discussion (see below) we think the link should basically just point to [the Icon update template](https://github.com/simple-icons/simple-icons/issues/new?assignees=&labels=icon+outdated&template=icon_update.md) as (a) this reduces the chances (prevents?) of someone creating many issues quickly in an automated way, and (b) while prefilling details such as the brand name is _nice_, it doesn't add to much value to the UX while adding a lot of HTML (at least one element per icon = at least 1900 elements).

**Comment by ericcornelissen** [comment]
I'm not sure what the value of adding "last updated" to each icon is to the "average" user (i.e. those that don't actively contribute to the project) and for that reason I'm not quite sure if we should add that to the website. If it's something you're personally interested in, I think you're better off looking to git for getting insight into what icons haven't been touched for a long time.

As for a "report outdated icon link": I do quite like the idea. Did you have anything in mind? I don't think it makes sense to add a button for this to each individual icon. It would allow us to embed the brand name in the issue link (allowing us to embed it in the issue title or body), but I don't expect it to be used all too often while adding over 1900 new elements to the website (not to mention that typing the brand name isn't that difficult :upside_down_face:). We could have a "section" with links like this, most notably "request a new icon" and  "report an outdated icon".

**Comment by jorgeamadosoria** [comment]
> We could have a "section" with links like this, most notably "request a new icon" and "report an outdated icon".

I love the menu section idea! 
The feature is not going to be used all that often, but it will be used by some people. I think that's easier for the run of the mill user than going to git and filing an issue.
I think of two ways: 
- A Pug template to report / request / feedback, accesible from the menu. Pro: more user friendly. Con: more work and code to maintain.
- Or simply link to github with an issue / request template. Pro: way easier to implement. Con: may be confusing for an user to jump from the website to github.

The second one is my favorite because of it's simplicity. I think it's safe to assume a certain level of expertise in the userbase. They shouldn't be scared of Github.


So, the last updated is perhaps not something for the website. The idea is to have that as an attribute of the icon. For what I see you guys do a review of the whole icon base every year or so, to make sure the icons are not obsolete.
A "last updated" timestamp would make it possible to check each icon as they are approaching staleness, say, every 6 months to a year. That way, when the time comes for a yearly review, you can cut down on the amount of icons that need to be checked. Now it may not be all that important, but I'm thinking ahead to when the library adds a couple thousand more icons.

**Comment by ericcornelissen** [comment]
> > We could have a "section" with links like this, most notably "request a new icon" and "report an outdated icon".
> 
> I love the menu section idea!
> The feature is not going to be used all that often, but it will be used by some people. I think that's easier for the run of the mill user than going to git and filing an issue.
> I think of two ways:
> 
>     * A Pug template to report / request / feedback, accesible from the menu. Pro: more user friendly. Con: more work and code to maintain.
> 
>     * Or simply link to github with an issue / request template. Pro: way easier to implement. Con: may be confusing for an user to jump from the website to github.
> 
> 
> The second one is my favorite because of it's simplicity. I think it's safe to assume a certain level of expertise in the userbase. They shouldn't be scared of Github.

Just because we want to keep all issues in GitHub anyway I think we should go with the second option.


> So, the last updated is perhaps not something for the website. The idea is to have that as an attribute of the icon. For what I see you guys do a review of the whole icon base every year or so, to make sure the icons are not obsolete.
> A "last updated" timestamp would make it possible to check each icon as they are approaching staleness, say, every 6 months to a year. That way, when the time comes for a yearly review, you can cut down on the amount of icons that need to be checked. Now it may not be all that important, but I'm thinking ahead to when the library adds a couple thousand more icons.

The icon review is not a "standard" process, and the one this year has a different focus from the one last year. Nor do I think it should be something we strive to as it's not always feasible (not at 2000 icons, definitely not at a bigger number) and not very productive.

If you want to propose adding a "last updated"-like timestamp to the icon data, that would deserve it's own issue in the main repo. But I can already tell you that, if it were solely up to me, will be rejected as this data is already available through git or GitHub. For example, If you want to see when a particular icon was last changed, simple run `git log icons/[ICON_NAME].svg` or go to GitHub and search for the icon you're interested in.

If you want more detailed "statistics" like you suggested, you can easily put together a script to leverage git's already available data to get the output you want.

**Comment by jorgeamadosoria** [comment]
> > > We could have a "section" with links like this, most notably "request a new icon" and "report an outdated icon".
> > 
> > 
> > I love the menu section idea!
> > The feature is not going to be used all that often, but it will be used by some people. I think that's easier for the run of the mill user than going to git and filing an issue.
> > I think of two ways:
> > ```
> > * A Pug template to report / request / feedback, accesible from the menu. Pro: more user friendly. Con: more work and code to maintain.
> > 
> > * Or simply link to github with an issue / request template. Pro: way easier to implement. Con: may be confusing for an user to jump from the website to github.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The second one is my favorite because of it's simplicity. I think it's safe to assume a certain level of expertise in the userbase. They shouldn't be scared of Github.
> 
> Just because we want to keep all issues in GitHub anyway I think we should go with the second option.
> 
> > So, the last updated is perhaps not something for the website. The idea is to have that as an attribute of the icon. For what I see you guys do a review of the whole icon base every year or so, to make sure the icons are not obsolete.
> > A "last updated" timestamp would make it possible to check each icon as they are approaching staleness, say, every 6 months to a year. That way, when the time comes for a yearly review, you can cut down on the amount of icons that need to be checked. Now it may not be all that important, but I'm thinking ahead to when the library adds a couple thousand more icons.
> 
> The icon review is not a "standard" process, and the one this year has a different focus from the one last year. Nor do I think it should be something we strive to as it's not always feasible (not at 2000 icons, definitely not at a bigger number) and not very productive.
> 
> If you want to propose adding a "last updated"-like timestamp to the icon data, that would deserve it's own issue in the main repo. But I can already tell you that, if it were solely up to me, will be rejected as this data is already available through git or GitHub. For example, If you want to see when a particular icon was last changed, simple run `git log icons/[ICON_NAME].svg` or go to GitHub and search for the icon you're interested in.
> 
> If you want more detailed "statistics" like you suggested, you can easily put together a script to leverage git's already available data to get the output you want.

the idea is to simplify the process of review. Github's will only tell you the last time an icon was updated, not the last time it was "looked at", which is the purpose of the field. Perhaps I misnamed it.
I thought the review was a yearly process, but if it isn't, that just means that this timestamp field is all the more important: we will only find outif an icon is obsolete if an user reports it, if we happen to look at it, or if we catch it in a review.
A timestamp will make sure that no icon goes more than 6 (3, 1?) months without being look at, thus making sure that all icons are going to be reviewed at some point to detect changes.

This, along with a "report icon" feature would do wonders in keeping the library up to date at any size, since you won't have to check all icons but only those that are reported and those that are stale.
GIthub won't help in this, I'm afraid.

**Comment by ericcornelissen** [comment]
> the idea is to simplify the process of review. Github's will only tell you the last time an icon was updated, not the last time it was "looked at", which is the purpose of the field.

Thanks for clarifying. I personally still disagree, but if this comment doesn't convince you otherwise I encourage to create an issue for this (summarizing what we already discussed here) in the main project both for visibility and because at this point it's a topic that only concerns the main project. I will update this issue to just cover adding a link to report outdated icons (do iterate on my rewrite if you feel like I missed something).

There are two reasons why I don't think this is needed, and one reason why I think this isn't a good/feasible idea. tl;dr: GitHub issues can manage this (to an extend); we can rely on users reporting outdated icons for us; keeping track of this in the codebase is either (a) unreliable, or (b) an unnecessary burden on maintainers and contributors alike; 

1. We already do kinda use GitHub for this. The "yearly review" issues and the "category review" issues (e.g. Google or Apache) are kind of a way of saying: when this issue is closed we signed off on all these icons being reviewed at this point in time. It's not perfect, but it gives a rough indication that's missing from the git log in case the icon was deemed up-to-date.
2. The easiest way to find out if an icon is outdated is to have a user of the library report it to us (which is why I love the other request of this issue). From my perspective there is no need to have the most up-to-date version of each log at all times. First, it is simply impossible with the amount of icons we have. Second, users **cannot** have this expectation from a free, volunteer-run project (if they do it is simply their problem if they're frustrated with the project). Third, it isn't even a real problem if a logo is a bit outdated, it will still be recognized. Fourth, it isn't even always clear if we should update immediately (see e.g. https://github.com/simple-icons/simple-icons/pull/6017).
3. Adding a "last checked" field in the code base has no value to anyone using the package (while we could strip it out before publishing, that seems like too much effort to me), not to mention that it is incredibly hard to accurately keep track of. Even if we get to a point where maintainers remember to update the "last checked" value of an icon (which I think is a burden that we shouldn't place on maintainers), there is no way we can get contributors to do this (which, again, I don't even think is something we should ask of them).

**Comment by jorgeamadosoria** [comment]
Point 2 is very convincing, with regards to the phrase "the logo even if outdated is still recognizable". That's true.
Point 3 is not an unsolvable problem. If we really wanted this field, there are ways to make it work without adding more work to maintainers.

But, this is not a huge problem. If you don't like it we can move on. As you said, there are other ways to more or less accomplish the same. So we can end that discussion here, no problem.

Now, about the link to report, I would very much like to work on that. I'm going to start by cloning the website and trying to add a report link to the menu. We can tweak the feature from that point forward until we are all satisfied.

**Comment by jorgeamadosoria** [comment]
Closed the PR after some discussion on the adequacy of having the report icon in the main menu (#96). After this, we have come to the conclusion that the report icon would be better added as an option on each card (perhaps detail view?) of each icon, using a flag svg.

**Comment by jorgeamadosoria** [comment]
Owing to the previous comment, this issue is blocked by #33
